// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repositories/error_repository.go

// Package mock_repositories is a generated GoMock package.
package mockports

import (
	reflect "reflect"

	domain "github.com/PyMarcus/TCC_SistemasDeInformacao2025/internal/core/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockError is a mock of Error interface.
type MockError struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMockRecorder
}

// MockErrorMockRecorder is the mock recorder for MockError.
type MockErrorMockRecorder struct {
	mock *MockError
}

// NewMockError creates a new mock instance.
func NewMockError(ctrl *gomock.Controller) *MockError {
	mock := &MockError{ctrl: ctrl}
	mock.recorder = &MockErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockError) EXPECT() *MockErrorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockError) Create(error_model *domain.Error) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", error_model)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockErrorMockRecorder) Create(error interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockError)(nil).Create), error)
}
